[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[cursor]
style.shape = "Underline"
style.blinking = "Always"

[window]
startup_mode = "Maximized"
decorations = "None"
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 3

[mouse]
hide_when_typing = true

[font]
size = 11.50

[font.normal]
#family = "MesloLGL Nerd Font Mono"
family = "BitstromWera Nerd Font Mono"
#family = "SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
  { key = "Right", mods = "Command", chars = "\u001BF" },
  { key = "Left",  mods = "Command", chars = "\u001BB" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "Return", mods = "Shift", chars = "\n" },
]

